### ISSUE TITLE
Suggestion: Output to clipboard.

### ISSUE THREAD

**Issue by sivan-koren** [maracko/json-to-go-vsc#2]
Thank you so much for making this extension!

I am not sure if it's possible to access the clipboard from a VS Code extension. It would be a very nice addition if that was an option in json-to-go-vsc.

**Comment by maracko** [comment]
Hey, thanks for using it and for the feedback! 
You mean outputting the result directly to clipboard? I don't think there should be any issues implementing that.

**Comment by maracko** [comment]
@sivan-koren do you want to give implementing this yourself a try?
The extension code is fairly simple and inside it you have an example of how you can use the clipboard object in the VS code API.
To get started fork the project, and when you are done with the change, submit a pull request to get it merged.

**Comment by sivan-koren** [comment]
I haven't worked in JS before so it might require some learning. If I get some time I may come back to this.

**Comment by maracko** [comment]
If you want it could be a good learning experience. If not, I can do it when I will have free time.

**Comment by maracko** [comment]
@sivan-koren this is now supported, cheers
