### ISSUE TITLE
 cannot paste when copying generics

### ISSUE THREAD

**Issue by newde36524** [maracko/json-to-go-vsc#6]
When I define generics, for example, copying [T any] to func A() as func[T any] A() will automatically pop up, and pressing esc will cancel the pasted [T any], can you cancel the detection of generics

**Comment by maracko** [comment]
Hey, thanks for the report.
I will look how it will be best to handle this. In the meantime you can undo the change made by the extension with ctrl/cmd+z or similar when it happens

**Comment by maracko** [comment]
@newde36524 I have pushed an update that should fix this. You can install either from VS code or github releases. 
Let me know if you still have issues.
